core/clubs/urls.py
from django.urls import path
from .views import home, club_details, project_details, searcher, features, team

app_name = 'clubs'
urlpatterns = [
    path('', home, name='home'),
    path('club_details/<int:pk>/', club_details, name='club_details'),
    path('project_details/<int:pk>/', project_details, name='project_details'),
    path('search/', searcher, name='searcher'),
    path('features/', features, name='features'),
    path('team/', team, name='team'),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clubs.urls', namespace='home')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/clubs/models.py
from django.db import models
from django.urls import reverse


def upload_img(instance, filename):
    return 'university_img/{0}/{1}'.format(instance.title, filename)


def upload_club_img(instance, filename):
    return 'club_img/{0}/{1}'.format(instance.club.title, filename)


def upload_project_img(instance, filename):
    return 'club_img/{0}/{1}/{2}'.format(instance.project.club.title, instance.project.title, filename)


class University(models.Model):
    abbreviation = models.CharField(max_length=10, default='Univer')
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to=upload_img)

    def __str__(self):
        return f"({self.abbreviation}) {self.title}"


class Club(models.Model):
    TYPES = (
        ('SR', 'Science and Research'),
        ('CC', 'Creativity and Culture'),
        ('SS', 'Social and Student development'),
        ('EM', 'Entertainment and Media'),
        ('SD', 'Sports and Dancing'),
        ('CH', 'Charity'),
        ('OT', 'Other')
    )
    university = models.ForeignKey(University, models.CASCADE, related_name='univ_club')
    faculty = models.CharField(max_length=200)
    type = models.CharField(max_length=2, choices=TYPES)
    title = models.CharField(max_length=200)
    date = models.DateField()
    description = models.TextField()
    contacts = models.TextField()

    def __str__(self):
        return f"{self.university} - {self.faculty}, {self.title}"

    def get_absolute_url(self):
        return reverse('clubs:club_details', kwargs={'pk': self.pk})


class Project(models.Model):
    club = models.ForeignKey(Club, models.CASCADE, related_name='projects')
    title = models.CharField(max_length=200)
    description = models.TextField()
    author = models.TextField(default='students')
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('clubs:project_details', kwargs={'pk': self.pk})


class Gallery(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='gallery')
    image = models.ImageField(upload_to=upload_club_img)

    def __str__(self):
        return self.club


class ProjectGallery(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='gallery')
    image = models.ImageField(upload_to=upload_project_img)

    def __str__(self):
        return self.project

core/clubs/views.py
from django.shortcuts import render, redirect

from .models import University, Club, Project


def home(request):
    universities = University.objects.all()
    clubs = Club.objects.all()
    return render(request, 'clubs/home.html', {'universities': universities,
                                               'clubs': clubs})


def club_details(request, pk):
    club = Club.objects.get(id=pk)
    return render(request, 'clubs/details.html', {'club': club})


def project_details(request, pk):
    project = Project.objects.get(id=pk)
    return render(request, 'clubs/project.html', {'project': project})


def searcher(request):
    inp = request.GET.get('search')
    rad = request.GET.get('search_by')
    u_results = None
    c_results = None
    if inp is str():
        return redirect('clubs:home')
    if rad == 'univ':
        u_results = University.objects.filter(title__icontains=inp)
    elif rad == 'club':
        c_results = Club.objects.filter(title__icontains=inp)
    return render(request, 'clubs/search.html', {'input': inp, 'universities': u_results, 'clubs': c_results})


def features(request):
    return render(request, 'features/soon.html')


def team(request):
    return render(request, 'about/team.html')

core/clubs/templates/clubs/details.html
{% extends 'base.html' %}

{% block main %}
{% endblock %}

{% block content %}
    <div class="container mb-5">
        <div class="row">
            <div class="col-12">
                <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{{ club.gallery.first.image.url }}" class="d-block mh-70 w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block pb-0 font-shadow">
                                <h2 class="isoct text-white font-weight-bold">{{ club.title }}</h2>
                                <div class="rect text-white font-weight-bold">
                                    <h4 class="mb-0">
                                        {{ club.university.title }}:{{ club.faculty }}
                                    </h4>
                                    <span class="h5 mb-0">{{ club.get_type_display }}</span>
                                </div>
                            </div>
                        </div>
                        {% for images in club.gallery.all|slice:"1:" %}
                        <div class="carousel-item ">
                            <img src="{{ images.image.url }}" class="d-block mh-70 w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block pb-0 font-shadow">
                                <h2 class="isoct text-white font-weight-bold">{{ club.title }}</h2>
                                <div class="rect text-white font-weight-bold">
                                    <h4 class="mb-0">
                                        {{ club.university.title }}:{{ club.faculty }}
                                    </h4>
                                    <span class="h5 mb-0">{{ club.get_type_display }}</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12">
                <hr class="border-dark">
                <h1 class="isoct font-weight-bold text-white text-center">{{ club.title }}</h1>
                <hr class="border-dark">
            </div>
            <div class="col-12 mt-3">
                <h5 class="isoct font-weight-bold text-white">
                    University:
                    <span class="text-muted">
                        {{ club.university.abbreviation }} ({{ club.university.title }})
                    </span>
                </h5>
                <h5 class="isoct font-weight-bold text-white">
                    Faculty: <span class="text-muted"> {{ club.faculty }}</span>
                </h5>
                <h5 class="isoct font-weight-bold text-white">
                    Type: <span class="text-muted">{{ club.get_type_display }}</span>
                </h5>
                <h5 class="isoct font-weight-bold text-white">
                    Date started: <span class="text-muted">{{ club.date|date:"SHORT_DATE_FORMAT" }}</span>
                </h5>
            </div>
            <div class="col-12 mt-3">
                <h5 class="isoct font-weight-bold text-white">
                    About us:
                </h5>
                <h4 class="text-white azote">{{ club.description}}</h4>
            </div>
            <div class="col-12 mt-3">
                <hr class="border-dark">
                <h2 class="isoct font-weight-bold text-white text-center">Our projects</h2>
                <hr class="border-dark">

                {% for project in club.projects.all %}
                <div class="col-6 mt-5">
                    <div class="card border-dark bg-transparent">
                        <img src="{{ project.gallery.first.image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <a href="{{ project.get_absolute_url }}" class="card-title isoct text-white">
                                <h4>{{ project.title }}</h4>
                            </a>
                            <p class="card-text rect text-muted">By: {{ project.author }}</p>
                            <hr>
                            <p class="card-text rect text-muted">{{ project.description|slice:"200" }} ...</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted card-text">Date started: {{ project.start_date }}</small>
                            <br>
                            <small class="text-muted card-text">Date ended: {{ project.end_date }}</small>
                        </div>
                    </div>
                  </div>
                {% endfor %}
            </div>
            <div class="col-12 mt-5">
                <hr class="border-dark">
                <h5 class="isoct font-weight-bold text-white">
                    Contacts: <span class="text-muted">{{ club.contacts }}</span>
                </h5>
            </div>
        </div>
    </div>
{% endblock %}

core/clubs/templates/clubs/home.html
{% extends 'base.html' %}

{% block content %}
<div id="carousel" class="carousel slide  mb-30" data-interval="false" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <hr class="border-dark">
            <h1 class="isoct font-weight-bold text-white text-center">All universities</h1>
            <hr class="border-dark">
            <div class="container mt-5">
                <div class="row">
                    {% for university in universities %}
                    <div class="col-6">
                        <div class="card mt-2 border-dark bg-transparent">
                            <div class="row no-gutters">
                                <div class="col-md-4">
                                    <img src="{{ university.image.url }}" class="card-img rounded-circle h-170" alt="">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <p class="card-title h3 isoct text-white">{{ university.abbreviation }}</p>
                                        <p class="card-text rect text-muted">{{ university.title }}</p>
                                        <p class="card-text rect text-muted">
                                            number of courses: {{ university.univ_club.all|length }}
                                        </p>
                                        <p class="card-text"><small class="text-muted"></small></p>
                                    </div>
                                </div>
                                <div class="col-12 mt-3 mb-9">
                                    <button class="btn btn-outline-primary rounded-0 btn-lg btn-block"
                                            data-toggle="collapse" data-target="#cl-clubs{{ university.id }}"
                                            aria-expanded="false" aria-controls="cl-clubs{{ university.id }}">
                                          View
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% for university in universities %}
                    <div class="col-6 pt-4">
                        <div class="collapse border border-dark rounded" id="cl-clubs{{ university.id }}">
                        {% for club in university.univ_club.all %}
                            <a href="{{ club.get_absolute_url }}" class="m-0">
                                <p class="pl-3 mb-0 pt-3">{{ club.title }}</p>
                            </a>
                            <small class="pl-3 text-muted">{{ club.faculty }}</small>
                            <hr class="border-dark ml-3 mr-3">
                        {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <hr class="border-dark">
            <h1 class="isoct font-weight-bold text-white text-center">All clubs</h1>
            <hr class="border-dark">
            <div class="container mt-5">
                <div class="row row-cols-1 row-cols-md-2">
                    {% for club in clubs %}
                    <div class="col-12">
                        <div class="card border-dark bg-transparent">
                            <img src="{{ club.gallery.first.image.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <a href="{{ club.get_absolute_url }}" class="card-title isoct text-white">
                                    <h4>{{ club.title }}</h4>
                                </a>
                                <p class="card-text rect text-muted">{{ club.get_type_display }}</p>
                                <p class="card-text rect text-muted">
                                    University: {{ club.university.abbreviation }} ({{ club.university.title }})
                                </p>
                                <p class="card-text rect text-muted">Faculty: {{ club.faculty }}</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted card-text">Date started: {{ club.date }}</small>
                            </div>
                        </div>
                      </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <a class="carousel-control-prev sticky-top float-left pt-5" href="#carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next sticky-top float-right  pt-5" href="#carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
{% endblock %}

core/clubs/templates/clubs/project.html
{% extends 'base.html' %}

{% block main %}
{% endblock %}

{% block content %}
    <div class="container mb-5">
        <div class="row">
            <div class="col-12">
                <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{{ project.gallery.first.image.url }}" class="d-block mh-70 w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block pb-0 font-shadow">
                                <h2 class="isoct text-white font-weight-bold">{{ project.title }}</h2>
                                <div class="rect text-white font-weight-bold">
                                    <h4 class="mb-0">
                                        {{ project.club.title }}:{{ project.club.get_type_display }}
                                    </h4>
                                    <span class="h5 mb-0">{{ project.club.faculty }}</span>
                                </div>
                            </div>
                        </div>
                        {% for images in project.gallery.all|slice:"1:" %}
                        <div class="carousel-item ">
                            <img src="{{ images.image.url }}" class="d-block mh-70 w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block pb-0 font-shadow">
                                <h2 class="isoct text-white font-weight-bold">{{ project.title }}</h2>
                                <div class="rect text-white font-weight-bold">
                                    <h4 class="mb-0">
                                        {{ project.club.title }}:{{ project.club.get_type_display }}
                                    </h4>
                                    <span class="h5 mb-0">{{ project.club.faculty }}</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12">
                <hr class="border-dark">
                <h1 class="isoct font-weight-bold text-white text-center">{{ project.title }}</h1>
                <hr class="border-dark">
            </div>
            <div class="col-12 mt-3">
                <h5 class="isoct font-weight-bold text-white">
                    Faculty: <span class="text-muted"> {{ project.club.faculty }}</span>
                </h5>
                <h5 class="isoct font-weight-bold text-white">
                    Club:
                    <span class="text-muted">
                        {{ project.club.title }} ({{ project.club.get_type_display }})
                    </span>
                </h5>
                <h5 class="isoct font-weight-bold text-white">
                    Date started: <span class="text-muted">{{ project.start_date|date:"SHORT_DATE_FORMAT" }}</span>
                </h5>
                <h5 class="isoct font-weight-bold text-white">
                    Date end(ed): <span class="text-muted">{{ project.end_date|date:"SHORT_DATE_FORMAT" }}</span>
                </h5>
            </div>
            <div class="col-12 mt-3 ">
                <h5 class="isoct font-weight-bold text-white">
                    About the project:
                </h5>
                <h4 class="text-white azote">{{ project.description}}</h4>
            </div>
            <div class="col-12 mt-5">
                <hr class="border-dark">
                <h5 class="isoct font-weight-bold text-white">
                    Author(s): <span class="text-muted">{{ project.author }}</span>
                </h5>
            </div>
        </div>
    </div>
{% endblock %}

core/clubs/templates/clubs/search.html
{% extends 'base.html' %}

{% block main %}
{% endblock %}

{% block content %}
<div class="container mb-5 mt-5">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="isoct text-white font-weight-bold mb-0">Results</h1>
            <h5 class="text-muted"> Of search: '{{ input }}'</h5>
        </div>
        {% if universities %}
        <div class="col-12 mb-5 mt-5">
            <hr class="border-dark">
            <h1 class="isoct font-weight-bold text-white text-center">All universities</h1>
            <hr class="border-dark">
        </div>
        <div class="col-12">
            {% for university in universities %}
            <div class="col-6">
                <div class="card mt-2 border-dark bg-transparent">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img src="{{ university.image.url }}" class="card-img rounded-circle h-170" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <p class="card-title h3 isoct text-white">{{ university.abbreviation }}</p>
                                <p class="card-text rect text-muted">{{ university.title }}</p>
                                <p class="card-text rect text-muted">
                                    number of courses: {{ university.univ_club.all|length }}
                                </p>
                                <p class="card-text"><small class="text-muted"></small></p>
                            </div>
                        </div>
                        <div class="col-12 mt-3 mb-9">
                            <button class="btn btn-outline-primary rounded-0 btn-lg btn-block" data-toggle="collapse"
                                    data-target="#cl-clubs{{ university.id }}"
                                    aria-expanded="false" aria-controls="cl-clubs{{ university.id }}">
                                  View
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% for university in universities %}
            <div class="col-6 pt-4">
                <div class="collapse border border-dark rounded" id="cl-clubs{{ university.id }}">
                {% for club in university.univ_club.all %}
                    <a href="{{ club.get_absolute_url }}" class="m-0"><p class="pl-3 mb-0 pt-3">{{ club.title }}</p></a>
                    <small class="pl-3 text-muted">{{ club.faculty }}</small>
                    <hr class="border-dark ml-3 mr-3">
                {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
        {% elif clubs %}
        <div class="col-12 mb-5 mt-5">
            <hr class="border-dark">
            <h1 class="isoct font-weight-bold text-white text-center">All clubs</h1>
            <hr class="border-dark">
        </div>
        {% for club in clubs %}
        <div class="col-12">
            <div class="col-6 mb-4">
                <div class="card border-dark bg-transparent">
                    <img src="{{ club.gallery.first.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{{ club.get_absolute_url }}" class="card-title isoct text-white">
                            <h4>{{ club.title }}</h4>
                        </a>
                        <p class="card-text rect text-muted">{{ club.get_type_display }}</p>
                        <p class="card-text rect text-muted">
                            University: {{ club.university.abbreviation }} ({{ club.university.title }})
                        </p>
                        <p class="card-text rect text-muted">Faculty: {{ club.faculty }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted card-text">Date started: {{ club.date }}</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-12 mt-5 mb-5">
            <hr class="border-dark">
            <h3 class="isoct text-white font-weight bold">
                Sorry, nothing was found, check the spelling or try to search for something else
            </h3>
            <hr class="border-dark">
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/icons.css' %}" rel="stylesheet" type="text/css" media="all" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/txt_typer.js' %}"></script>
    <link rel="shortcut icon" href="">
</head>
<body class="bg-dark-m">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark2-m">
    <a class="navbar-brand isoct font-weight-bold " href="{% url 'clubs:home' %}">Fanat</a>
    <button class="navbar-toggler" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link isoct" href="{% url 'clubs:home' %}">Home</a>
        </li>
    </ul>
    <button class="btn pb-0 btn-outline-primary" type="button"
            data-toggle="collapse" data-target="#cl-search" aria-expanded="false" aria-controls="cl-search">
        <i class="bi bi-search"></i>
    </button>
</nav>
<div class="collapse" id="cl-search">
    <div class="container mt-5 pt-5 mb-5">
        <div class="row justify-content-md-center">
            <div class="col-11"></div>
            <div class="col-1">
               <button class="btn btn-sm pb-0 btn-outline-primary" type="button"
                        data-toggle="collapse" data-target="#cl-search" aria-expanded="false" aria-controls="cl-search">
                    <i class="bi bi-x text-white"></i>
                </button>
            </div>
            <div class="col col-lg-8 mt-5">
                <form class="" method="get" action="{% url 'clubs:searcher' %}">
                    <div class="input-group">
                        <input class="form-control form-control-lg" name="search" type="text" placeholder="Search">
                        <div class="input-group-append">
                            <button class="btn btn-outline-primary" type="submit">Search</button>
                        </div>
                    </div>
                    <br>
                    <div class="col-md-4 offset-md-4 text-white">
                        <div class="form-check form-check-inline ">
                            <input class="form-check-input" type="radio" name="search_by" id="univ" value="univ">
                            <label class="form-check-label" for="univ">University</label>
                        </div>

                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="search_by" id="club" value="club">
                            <label class="form-check-label" for="club">Club</label>
                        </div>
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% block main %}
<div class="container-fluid mb-5">
    <div class="row">
        <div class="col-lg-6 pl-5">
            <div class="mb-5 h-200">
                <h1 class="display-4 isoct font-weight-bold mt-4">
                    <span class="text-white">With Fanat you can</span>
                    <span class="typewrite font-sp text-primary underline" data-period="3000"
                          data-type='[ "create a new community.", "find friends.", "improve skills."]'>
                    </span>
                </h1>
            </div>
            <h5 class="isoct text-white mb-3">Fanat will help you find/create university or non-university clubs</h5>
        </div>
        <div class="col-lg-6">
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
{% endblock %}
<footer class="container py-5">
    <div class="row">
        <div class="col-12 col-md">
            <small class="d-block mb-3 text-muted">© 2020-2020</small>
        </div>
        <div class="col-6 col-md">
            <h5 class="isoct font-weight-bold text-white">Features</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'clubs:features' %}">Cool stuff</a></li>
                <li><a class="text-muted" href="{% url 'clubs:features' %}">Random feature</a></li>
                <li><a class="text-muted" href="{% url 'clubs:features' %}">Team feature</a></li>
                <li><a class="text-muted" href="{% url 'clubs:features' %}">Stuff for developers</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5 class="isoct font-weight-bold text-white">Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted"
                       href="https://careersblog.enterprise.co.uk/why-you-should-join-clubs-and-societies-at-university/">
                    About clubs
                </a></li>
                <li><a class="text-muted" href="https://www.youtube.com/watch?v=5qap5aO4i9A">Music</a></li>
                <li><a class="text-muted" href="#"></a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5 class="isoct font-weight-bold text-white">Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="https://edu.gov.kg/ru/">Education</a></li>
                <li><a class="text-muted" href="https://store.steampowered.com/agecheck/app/782330/">Gaming</a></li>
                <li> <a class="text-muted" href="http://www.onlinewebfonts.com">Online web fonts</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5 class="isoct font-weight-bold text-white">About</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'clubs:team' %}">Team</a></li>
                <li><a class="text-muted" href="{% url 'clubs:home' %}">Other projects</a></li>
            </ul>
        </div>
    </div>
</footer>
</body>
</html>

core/universities/templates/universities/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
</div>
{% endblock %}